### ISSUE TITLE
Scan html files and produce css usage report

### ISSUE THREAD

**Issue by izhaqba** [zivl/gulp-css-usage#1]
Hi,
I was wondering if is it possibale can scan .html files and generate the CSS usage report for that.
The only example i saw is to check usage based .js files.

Thanks.

**Comment by zivl** [comment]
you are right. it was first build to serve JS frameworks. I'll add this option as well :)
hopefully to do it in the next days...
stay tuned!

**Comment by zivl** [comment]
HTML files support pushed in version 2.0.2
